version: '3.5'
services:
  frontend:
    container_name: rollcall-frontend
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    environment:
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXT_PUBLIC_URL: ${NEXT_PUBLIC_URL}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    # ports:
    #   - "3000:3000"
    expose:
      - 3000
    networks:
      - nextjs

  nginx:
    container_name: rollcall-frontend-nginx
    build: ./nginx
    restart: unless-stopped
    volumes:
      - ./log:/var/log/nginx
    networks:
      - proxy
      - nextjs
    depends_on:
      - frontend
    environment:
      - VIRTUAL_HOST=rollcall.jefferyho.cc
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=rollcall.jefferyho.cc
      - LETSENCRYPT_EMAIL=chiachun2491@gmail.com

networks:
  proxy:
    external:
      name: self-nginx-proxy
  nextjs:
    name: nextjs
    driver: bridge
